name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Start PHP Built-in Server
      run: |
        php -S 0.0.0.0:8000 -t public &

